#pragma once

// @generated by aten/src/ATen/gen.py from MetaFunctions.h

#include <ATen/ATen.h>  // TODO: improve
#include <ATen/TensorMeta.h>

namespace at {
namespace meta {

CAFFE2_API TensorMeta upsample_nearest1d(const Tensor & self, IntArrayRef output_size, c10::optional<double> scales);
CAFFE2_API TensorMeta upsample_nearest1d_backward(const Tensor & grad_output, IntArrayRef output_size, IntArrayRef input_size, c10::optional<double> scales);

} // namespace meta
} // namespace at
